/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.crud_access;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pelay
 */
public class CrudDesign extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrudDesign.class.getName());
    Connection con;
    /**
     * Creates new form CrudDesign
     */
    public CrudDesign() {
        initComponents();
        connect();
        loadData();
    }
    public void connect() {

    try {

        String url = "jdbc:ucanaccess://C:\\Users\\pelay\\OneDrive\\Pictures\\Documents\\Crud_Access\\Crud_Access.accdb";

        con = DriverManager.getConnection(url);

        System.out.println("Connected!");

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e.getMessage());

    }
}
public void loadData() {

    try {

        String sql = "SELECT * FROM Students";

        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(sql);

        DefaultTableModel model =
                (DefaultTableModel) tblStudents.getModel();

        model.setRowCount(0);

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getString("ID"),
                rs.getString("name"),
                rs.getString("section"),
                rs.getString("course")
            });
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e.getMessage());

    }
}    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCourse = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtSection = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("STUDENT CRUD");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 180, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Course:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Student ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 90, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Section:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        getContentPane().add(txtCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 120, -1));

        txtID.addActionListener(this::txtIDActionPerformed);
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 120, -1));
        getContentPane().add(txtSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 120, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 120, -1));

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        btnClear.setText("CLEAR");
        btnClear.addActionListener(this::btnClearActionPerformed);
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        btnCreate.setText("CREATE");
        btnCreate.addActionListener(this::btnCreateActionPerformed);
        getContentPane().add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Section", "Course"
            }
        ));
        tblStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudents);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 400, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
    try {

    String sql = "INSERT INTO Students (name, section, course) VALUES (?, ?, ?)";

    java.sql.PreparedStatement pst = con.prepareStatement(sql);

    pst.setString(1, txtName.getText());
    pst.setString(2, txtSection.getText());
    pst.setString(3, txtCourse.getText());

    pst.executeUpdate();

    JOptionPane.showMessageDialog(this, "Student added successfully!");

    loadData();

    txtName.setText("");
    txtSection.setText("");
    txtCourse.setText("");

    } catch (Exception e) {

    JOptionPane.showMessageDialog(this, e.getMessage());

}
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
    try {

    String sql = "UPDATE Students SET name=?, section=?, course=? WHERE ID=?";

    java.sql.PreparedStatement pst = con.prepareStatement(sql);

    pst.setString(1, txtName.getText());
    pst.setString(2, txtSection.getText());
    pst.setString(3, txtCourse.getText());
    pst.setInt(4, Integer.parseInt(txtID.getText()));

    pst.executeUpdate();

    JOptionPane.showMessageDialog(this, "Student updated successfully!");

    loadData();

    } catch (Exception e) {

    JOptionPane.showMessageDialog(this, e.getMessage());

}
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    try {

    String sql = "DELETE FROM Students WHERE ID=?";

    java.sql.PreparedStatement pst = con.prepareStatement(sql);

    pst.setInt(1, Integer.parseInt(txtID.getText()));

    pst.executeUpdate();

    JOptionPane.showMessageDialog(this, "Student deleted successfully!");

    loadData();

    txtID.setText("");
    txtName.setText("");
    txtSection.setText("");
    txtCourse.setText("");

    } catch (Exception e) {

    JOptionPane.showMessageDialog(this, e.getMessage());

}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
    txtID.setText("");
    txtName.setText("");
    txtSection.setText("");
    txtCourse.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void tblStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentsMouseClicked
    int row = tblStudents.getSelectedRow();

    txtID.setText(tblStudents.getValueAt(row, 0).toString());
    txtName.setText(tblStudents.getValueAt(row, 1).toString());
    txtSection.setText(tblStudents.getValueAt(row, 2).toString());
    txtCourse.setText(tblStudents.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tblStudentsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CrudDesign().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextField txtCourse;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSection;
    // End of variables declaration//GEN-END:variables
}
